version: "2.3"

services:
  postgres:
    container_name: service-postgres
    image: postgres:12
    environment: &db_env
      POSTGRES_DB: wj_service_template_db_1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    volumes:
      - ./postgresql/schemas:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - postgres

  wj_service_template-container:
    image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
    privileged: true
    environment:
      <<: *db_env
      PREFIX: ${PREFIX:-~/.local}
      CCACHE_DIR: /wj_service_template/.ccache
      CORES_DIR: /cores
    volumes:
      - .:/wj_service_template:rw
      - ${TC_CORES_DIR:-./.cores}:/cores:rw
    ports:
      - 8080:8080
    working_dir: /wj_service_template
    entrypoint:
      - ./tests/run_as_user.sh
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
